services:

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - educore-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - educore-network

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    restart: always
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - educore-network

  zipkin:
    image: openzipkin/zipkin:3
    restart: always
    ports:
      - "9411:9411"
    networks:
      - educore-network

  eureka-server:
    build: ./educore-eureka-server
    restart: always
    ports:
      - "8761:8761"
    networks:
      - educore-network

  auth-service:
    build: ./educore-auth-service
    container_name: auth-service
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/auth_db?createDatabaseIfNotExist=true&useSSL=false
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    ports:
      - "8081:8081"
    networks:
      - educore-network

  student-service:
    build: ./educore-student-service
    restart: always
    depends_on:
      - mysql
      - kafka
      - eureka-server
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/student_db
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    ports:
      - "8082:8082"
    networks:
      - educore-network

  grade-service:
    build: ./educore-grade-service
    restart: always
    depends_on:
      - mysql
      - kafka
      - eureka-server
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/grade_db
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    ports:
      - "8083:8083"
    networks:
      - educore-network

  analytics-service:
    build: ./educore-analytics-service
    restart: always
    depends_on:
      - mysql
      - kafka
      - eureka-server
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/analytics_db
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    ports:
      - "8084:8084"
    networks:
      - educore-network

  api-gateway:
    build: ./educore-api-gateway
    restart: always
    depends_on:
      - eureka-server
    env_file:
      - .env
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    ports:
      - "8080:8080"
    networks:
      - educore-network

  frontend:
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - api-gateway
    env_file:
      - .env
    environment:
      VITE_API_BASE_URL: http://localhost:8080
    ports:
      - "3000:3000"
    networks:
      - educore-network

volumes:
  mysql_data:

networks:
  educore-network:
    driver: bridge